# Generated by Django 3.0.3 on 2020-03-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('categoryName', models.TextField(max_length=20)),
            ],
        ),
    ]
