# Generated by Django 3.0.3 on 2020-03-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(choices=[('c', 'cash'), ('v', 'visa')], max_length=50)),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField(default=1)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'unique_together': {('userID', 'productID', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(choices=[('c', 'cash'), ('v', 'visa')], max_length=50)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'unique_together': {('productID', 'userID')},
            },
        ),
    ]
