# Generated by Django 3.0.4 on 2020-03-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.Product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.User')),
            ],
            options={
                'unique_together': {('productID', 'userID')},
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(choices=[('c', 'cash'), ('v', 'visa')], max_length=50)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.Product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.User')),
            ],
            options={
                'unique_together': {('userID', 'productID')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.User')),
            ],
            options={
                'unique_together': {('userID', 'address')},
            },
        ),
    ]
