# Generated by Django 3.0.3 on 2020-03-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '__first__'),
        ('User', '__first__'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'unique_together': {('productID', 'userID')},
            },
        ),
    ]
