# Generated by Django 3.0.3 on 2020-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.TextField(default='test'),
        ),
    ]
