# Generated by Django 3.0.4 on 2020-03-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20200304_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
