# Generated by Django 3.0.3 on 2020-03-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('userImage', models.ImageField(upload_to='user/')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
